# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'skrisliu-github-io'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-L19XLR03TJ'

menu:
- {name: 'home', url: }
- {name: 'publications', url: 'publications.html'}
- {name: 'visual', url: 'visual.html'}
#- {name: 'contact', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'google',     link: 'https://scholar.google.com/citations?hl=en&user=D2ZRcjQAAAAJ'}
#- {icon: 'github',     link: 'https://www.github.com/skrisliu'}
#- {icon: 'twitter',    link: 'https://twitter.com/skrisliu'}
- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/skrisliu/'}
- {icon: 'envelope',   link: 'mailto:skrisliu@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
# pagination:
# next_page: 'Newer'
# previous_page: 'Older'

#sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy:'

#post_date_prefix: 'Written on'
